#include <detpic32.h>

int main(void){
	//CONFIGURAR PORTO RD11 COMO SAIDA DIGITAL
	TRISDbits.TRISD11=0;		//DESLIGAR DIGITAL OUTPUT
	AD1PCFGbits.PCFG11=1; 		//CONFIGURAR COMO ENTRADA ANALOGICA
	AD1CON1bits.SSRC=7;
	AD1CON1bits.CLRASAM=1;		//CLEAR ASAM
	AD1CON3bits.SAMC=16;
	AD1CON2bits.SMPI=1-1;		//INTERRUPR AFTER N SAMPLES (N-1)
	AD1CHSbits.CH0SA=11;		//SELECIONA CANAL COMO INPUT PARA O A/D CONVERTER
	AD1CON1bits.ON=1;		//LIGA AD CONVERTER(ULTIMA INSTRUÇÃO)
	
	volatile int aux;
	while(1){
		AD1CON1bits.ASAM=1;
		LATDbits.LATD11=1;
		while(IFS1bits.AD1IF==0);
		LATDbits.LATD11=0;
		aux= ADC1BUF0;
		printInt(aux, 16|3<<16);
		IFS1bits.AD1IF=0;
	}



	return 0;
}
